default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ol_development
  host: localhost

test:
  <<: *default
  database: ol_test

production:
  <<: *default
  database: ol_production
