# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9800474c5a010df65974822455e12d17bec72b7e8ab0db9ae999dc38cac5f9770d6f6aa92aa18049ea495cb1a120346a188a5cd3e17c376cd348c1e8907f1f9

test:
  secret_key_base: 97201077faf1bf40461e0f7ce7959743ae69df534ee6235521dc4f3341df1ad36c11142d9d57eea9c4c068efbc8fcf8d56ed9e61d0b99a5da0a388a2f1446d01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
